# Generated by Django 5.1.5 on 2025-03-22 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_latitude', models.FloatField(blank=True, null=True)),
                ('origin_longitude', models.FloatField(blank=True, null=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('cng', 'CNG'), ('car', 'Car')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
