# Generated by Django 5.1.7 on 2025-03-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='content',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
