# Generated by Django 5.1.6 on 2025-03-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_ride_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
